services:
  stepfunctions:
    image: amazon/aws-stepfunctions-local
    ports:
      - '8083:8083'
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-west-2
    command: ['-jar', 'StepFunctionsLocal.jar']
